sudo: required

language: python

services:
    - docker

before_script:
- "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
    - make cunit-test integration
    - "fossa --option allow-unresolved:true" 
