sudo: required

language: go

go:
  - 1.14

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install python3-setuptools python3-pip python3
  - pip3 install virtualenv --user

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

env:
  global:
    - PATH=/opt/python/3.7.1/bin:~/.local/bin:$PATH
    - GOPATH="" GO111MODULE=on

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script:
        - "chmod -R a+rw . || true"
        - "make cunit-test"
    - name: "Integration Tests"
      script:
        - "chmod -R a+rw . || true"
        - ls /opt/python/3.7.1/bin && python --version && which virtualenv
        - "make integration"
    - stage: "Compliance"
      name: "Fossa Check"
      script:
        - "chmod -R a+rw . || true"
        - "fossa --option allow-unresolved:true"
